name: CI

on:
  issues:
    types: [ opened, edited ]
env:
  MY_ENV_VAR: patata

jobs:
  change-env-var-value:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: add label to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['test-label']
              });  
      - name: previous value
        run: echo "$MY_ENV_VAR!"
      - id: change
        name: change-env-var-value
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.MY_ENV_VAR);
            process.env.MY_ENV_VAR="Frita";
            console.log(process.env.MY_ENV_VAR);
            return process.env.MY_ENV_VAR;
          result-encoding: string
      - name: set-new-value
        run: |
          echo "MY_ENV_VAR = ${{steps.change.outputs.result}}" >> $MY_ENV_VAR
          echo ${{ env.MY_ENV_VAR }}
  #validation:
  #  needs: change-env-var-value
  #  runs-on: ubunto-20.04
  #  steps:
  #    - name: success final value
  #      run: echo "${{ env.MY_ENV_VAR }}"
