name: CI

on:
  issues:
    types: [ opened ]
env:
  MY_ENV_VAR: patata

jobs:
  change-env-var-value:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: add label to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['test-label']
              });  
      - name: previous value
        run: echo "$MY_ENV_VAR!"
      - name: change env var value
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.MY_ENV_VAR);
            process.env.MY_ENV_VAR='PatataFrita';
            console.log(process.env.MY_ENV_VAR);
  value-checker:
    needs: change-env-var-value
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: success final value
        if: ${{ env.MY_ENV_VAR }} == 'PatataFrita'
        run: echo "MY ENV VAR values:${{ env.MY_ENV_VAR }}"
      - name: failure final value
        if: ${{ env.MY_ENV_VAR }} != 'PatataFrita'
        run: exit 1
