name: CI

on:
  issues:
    types: [ opened, commented ]
env:
  MY_ENV_VAR: patata

jobs:
  change-env-var-value:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: add label to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['test-label']
              });  
      - name: previous value
        run: echo "$MY_ENV_VAR!"
      - id: change
        name: change-env-var-value
        uses: actions/github-script@v6
        with:
          script: |
            console.log(process.env.MY_ENV_VAR);
            process.env.MY_ENV_VAR="Frita";
            console.log(process.env.MY_ENV_VAR);
            return 'Frita';
          result-encoding: string
      - name: set-new-value
        run: ${{ env.MY_ENV_VAR }} < ${{steps.change.outputs.result}}
        
  value-checker:
    needs: change-env-var-value
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - name: success final value
        if: ${{ env.MY_ENV_VAR == 'Frita' }}
        run: echo "MY ENV VAR values:${{ env.MY_ENV_VAR }}"
      - name: failure final value
        if: ${{ env.MY_ENV_VAR != 'Frita' }}
        run: |
          echo "ENV VAR NOT MODIFIED: ${{ env.MY_ENV_VAR }}"
          exit 1
