name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV_VAR: patata

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      #- name: get github context
      #  run:   echo "$GITHUB_CONTEXT"
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: (${{ github.event.comment.body }}
      - name: release package
        if: steps.split.outputs._0 == '/release'
        uses: actions/create-release@latest
        with:
          release_name: Release ${{ steps.split.outputs._1 }}
          tag_name: ${{ steps.split.outputs._2 }}
      - name: get pull request comment
        run: echo ${{ github.event.comment.body }}
