name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV: DEFAULT_ENV
  MY_IMAGE: IMAGEN_ULTIMA

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
      - id: get_env_and_image
        name: get_env_and_image
        if: ${{ steps.split.outputs._0 }} == "/deploy" and ${{ steps.split.outputs._1 }} == "--env" and ${{ steps.split.outputs._3 }} == "--image"
        run: |
          export MY_ENV=${{ steps.split.outputs._2 }}
          echo MY_ENV
          export MY_IMAGE=${{ steps.split.outputs._4 }}
          echo MY_IMAGE
          
        #with:
          #entorno: ${{ steps.split.outputs._2 }}
          #imagen: ${{ steps.split.outputs._4 }}
      #- id: get_env_and_latest_image
      #  name: get_env_and_image
      #  if: ${{ steps.split.outputs._0 }} == "/deploy" and ${{ steps.split.outputs._1 }} == "--env" and ${{ steps.split.outputs._3 }} != "--image"
      #  with:
      #    entorno: ${{ steps.split.outputs._2 }}
      #    imagen: MY_ENV
      #- id: result
      #  name: result
      #  uses: actions/github-script@v6
      #  with:
      #    script: |
      #      console.log(${{ github.event.comment.body }});
      #      console.log(process.env.MY_ENV);
      #      console.log(process.env.MY_IMAGE);
