name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV: DEFAULT_ENV
  MY_IMAGE: IMAGEN_ULTIMA

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
      - id: get_env
        name: get_env
        if: ${{ steps.split.outputs._1 }} == "--env"
        uses: actions/github-script@v6
        with:
          script: |
            entorno = ${{ steps.split.outputs._2 }};
            console.log(entorno);
      - id: get_image
        name: get_image
        if: ${{ steps.split.outputs._3 }} == "--image"
        uses: actions/github-script@v6
        with:
          script: |
            imagen = ${{ steps.split.outputs._4 }};
            console.log(imagen);
      - name: get pull request comment
        run: echo ${{ github.event.comment.body }}
