name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV: DEFAULT_ENV
  MY_IMAGE: IMAGEN_ULTIMA

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
      - id: last_step
        name: last_step
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ github.event.comment.body }});
            process.env.MY_ENV = ${{ steps.split.outputs._2 }};
            if(${{ steps.split.outputs._3 }} == "--image"){
              process.env.MY_IMAGE = ${{ steps.split.outputs._4 }};
            }
            console.log(process.env.MY_ENV);
            console.log(process.env.MY_IMAGE);
      - name: get pull request comment
        run: echo ${{ github.event.comment.body }}
