name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV: DEFAULT_ENV
  MY_IMAGE: IMAGEN_ULTIMA
  LATEST_IMAGE: true

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
      - id: get_env_and_image
        name: get_env_and_image
        if: ${{ steps.split.outputs._0 }} == "/deploy") && ${{ steps.split.outputs._1 }} == "--env") && ${{ steps.split.outputs._3 }} == null)
        run: |
          echo "STATUS: " $LATEST_IMAGE
          export LATEST_IMAGE=false
          echo "COMMENT: " ${{ github.event.comment.body }}
          export MY_ENV=${{ steps.split.outputs._2 }}
          echo "ENTORNO: " $MY_ENV
          export MY_IMAGE=${{ steps.split.outputs._4 }}
          echo "IMAGEN: " $MY_IMAGE
      - id: get_env_and_latest_image
        name: get_env_and_latest_image
        if: env.LATEST_IMAGE == true
        run: |
          echo "STATUS: " $LATEST_IMAGE
          echo "COMMENT: " ${{ github.event.comment.body }}
          export MY_ENV=${{ steps.split.outputs._2 }}
          echo "ENTORNO: " $MY_ENV
          export MY_IMAGE=${{ steps.split.outputs._4 }}
          echo "IMAGEN: " $MY_IMAGE        
