name: CICD Comment launch

on:
  issue_comment:
    types: [created]
    
env:
  MY_ENV: DEFAULT_ENV
  MY_IMAGE: IMAGEN_ULTIMA

jobs:
  get-comment:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
      #- name: get github context
      #  run:   echo "$GITHUB_CONTEXT"
      #  env:
      #    GITHUB_CONTEXT: ${{ toJson(github) }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.event.comment.body }}
      - name: get comment values
        if: steps.split.outputs._0 == '/deploy --env'
        with:
          MY_ENV: ${{ steps.split.outputs._1 }}
          MY_IMAGE: ${{ steps.split.outputs._2 }}
      - id: last step
        name: last step
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ github.event.comment.body }});
            console.log(process.env.MY_ENV_VAR);
            console.log(process.env.MY_IMAGE);
      - name: get pull request comment
        run: echo ${{ github.event.comment.body }}
