name: Wait time

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    uses: afajardomorera/actions-tests/.github/workflows/workflow_dispatch.yml@main
    with:
      parametro1: FEDERICO
  simulation:
    runs-on: ubuntu-latest
    needs: deploy
    env: 
      VALID_BRANCH: true
    steps:
      - name: check_valid_branch
        run: echo echo "VALID_BRANCH=${{ startsWith('$GITHUB_HEAD_REF','feature') }}" >> $GITHUB_ENV
      - name: get-repo-name
        run: |
          echo "VALID BRANCH: " ${{ env.VALID_BRANCH }}
          echo "Repo name: " ${{ github.event.repository.name }}
          echo "Branch name: " $GITHUB_HEAD_REF
      #- name: Sleep for 30 seconds
      #  uses: jakejarvis/wait-action@master
      #  with:
      #    time: '3s'
      #- name: add_done_label_when_finish_successfully
      #  uses: actions-ecosystem/action-add-labels@v1
      #  with:
      #    labels: READY_FOR_DEPLOY
      #- name: mostrar-saludo
      #  run: |
      #    echo ${{ needs.deploy.outputs.saludo }}
