name: Wait time

on:
  workflow_call:
    inputs:
      time: 
        type: string
  
jobs:
  simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for ${{ inputs.time }} seconds
        uses: jakejarvis/wait-action@master
        with:
          time: ${{ inputs.time }}
  
  #deploy:
  #  uses: afajardomorera/actions-tests/.github/workflows/workflow_dispatch.yml@main
  #  with:
  #    parametro1: FEDERICO
  
      #- name: print_branch_name
      #  if: ${{ startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    echo "Rama: " $RAMA
      #- name: check_valid_branch
      #  if: ${{ !startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    exit 1
      #- name: Sleep for 30 seconds
      #  uses: jakejarvis/wait-action@master
      #  with:
      #    time: '3s'
      #- name: add_done_label_when_finish_successfully
      #  uses: actions-ecosystem/action-add-labels@v1
      #  with:
      #    labels: READY_FOR_DEPLOY
      #- name: mostrar-saludo
      #  run: |
      #    echo ${{ needs.deploy.outputs.saludo }}
