name: Wait time

on:
  pull_request:
    branches:
      - develop
env:
  RAMA: NOMBRE
jobs:
  deploy:
    uses: afajardomorera/actions-tests/.github/workflows/workflow_dispatch.yml@main
    with:
      parametro1: FEDERICO
  simulation:
    runs-on: ubuntu-latest
    needs: deploy
    env: 
      VALID_BRANCH: true
    steps:
      - name: get-repo-name
        run: |
          echo "Repo name: " ${{ github.event.repository.name }}
          echo "Branch name: " $GITHUB_HEAD_REF
          echo "RAMA=${{ env.GITHUB_HEAD_REF }}" >> $GITHUB_ENV
          echo "RAMA: " ${{ env.GITHUB_HEAD_REF }}
          echo "RAMA: " ${{ github.event.inputs.from_branch }}
          echo "Rama empieza main: " ${{ startsWith('env.RAMA', 'main') }}
          echo "Rama empieza patata: " ${{ startsWith('$RAMA', 'patata') }}
          echo "test empieza por te: " ${{ startsWith('test', 'te') }}
          echo "test empieza por pa: " ${{ startsWith('test', 'pa') }}
      #- name: print_branch_name
      #  if: ${{ startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    echo "Rama: " $RAMA
      #- name: check_valid_branch
      #  if: ${{ !startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    exit 1
      #- name: Sleep for 30 seconds
      #  uses: jakejarvis/wait-action@master
      #  with:
      #    time: '3s'
      #- name: add_done_label_when_finish_successfully
      #  uses: actions-ecosystem/action-add-labels@v1
      #  with:
      #    labels: READY_FOR_DEPLOY
      #- name: mostrar-saludo
      #  run: |
      #    echo ${{ needs.deploy.outputs.saludo }}
