name: Wait time

on:
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
      with:
        labels: DONE
