name: Wait time

on:
  pull_request:
    branches:
      - develop
env:
  RAMA: NOMBRE
jobs:
  deploy:
    uses: afajardomorera/actions-tests/.github/workflows/workflow_dispatch.yml@main
    with:
      parametro1: FEDERICO
  simulation:
    runs-on: ubuntu-latest
    needs: deploy
    env: 
      RAMA: rama
    steps:
      - name: get-repo-name
        run: |
          echo "Repo name: " ${{ github.event.repository.name }}
          echo "Branch name: " $GITHUB_HEAD_REF
          echo "RAMA=$GITHUB_HEAD_REF" >> $GITHUB_ENV
          echo "NOMBRE RAMA: " ${{ github.event.inputs.from_branch }}
          
      - name: rama
        run: |
          echo "RAMA: " $RAMA
          echo "Rama empieza mai: " ${{ startsWith(env.RAMA, 'mai') }}
          echo "Rama NO empieza patata: " ${{ !startsWith(env.RAMA, 'patata') }}
          
      - name: Check_NO_empieza_por_mai
        if: ${{ !startsWith(env.RAMA, 'mai') }}
        run: |
          echo "NO"
      - name: Check_empieza_por_mai
        if: ${{ startsWith(env.RAMA, 'mai') }}
        run: |
          echo "SI" $(git rev-parse --short "$GITHUB_SHA")
          
      #- name: print_branch_name
      #  if: ${{ startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    echo "Rama: " $RAMA
      #- name: check_valid_branch
      #  if: ${{ !startsWith('{{ env.RAMA }}', 'main') }}
      #  run: |
      #    exit 1
      #- name: Sleep for 30 seconds
      #  uses: jakejarvis/wait-action@master
      #  with:
      #    time: '3s'
      #- name: add_done_label_when_finish_successfully
      #  uses: actions-ecosystem/action-add-labels@v1
      #  with:
      #    labels: READY_FOR_DEPLOY
      #- name: mostrar-saludo
      #  run: |
      #    echo ${{ needs.deploy.outputs.saludo }}
