name: Wait time

on:
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: Sleep for 30 seconds
    #   uses: jakejarvis/wait-action@master
    #   with:
    #     time: '1s'
    - name: add_done_label_when_finish_successfully
      uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: READY_FOR_DEPLOY
    - name: check_labels_gh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pwd
        gh label list
       # labels=`gh label list`
       # echo "::set-output name=Labels::$labels"
    - name: see_result
      run: echo ${{ steps.check_labels_gh.outputs.labels }}
    # - name: get_labels
#       uses: actions/github-script@v4
#       with:
#         script: |
#           const request = {
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               pull_number: context.issue.number,
#               current_context: context
#             }
#           const token = core.getInput("github-token", { required: true })
#           core.info(`Token: ${token}`)
#           core.info(`Current Context: `)
#           core.info(` ${current_context} `)
          
          
          
