name: Wait time

on:
  pull_request:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: DONE
    - uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        one_of: DONE
        repo_token: ${{ secrets.GITHUB_TOKEN }}
