name: '[PR main] Call required checks'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - deploy*

jobs:
  main-pull-request:
    uses: afajardomorera/actions-tests/.github/workflows/delay_on_pr.yml@main
    with:
      time: 30s
