name: '[PR main] Call required checks'

on:
  pull_request:
    branches:
      - main
  issue_comment:
    types: [created]

jobs:
  main-pull-request:
    uses: ./.github/workflows/delay_on_pr.yml
    with:
      time: 30s
