name: LIQUIBASE-VALIDATOR
on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: checkout
        name: "Check Out del Código"
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Liquibase File Validator
        id: liquibase_validator
        uses: afajardomorera/liquibase-file-validator@v.1.5.5
        with:
          file: 'test.sql'
      # Use the output from the `hello` step
      - name: Get result
        run: |
          echo "VALID FILES: ${{ steps.liquibase_validator.outputs.validFiles }}"
          echo "INVALID FILES: ${{ steps.liquibase_validator.outputs.invalidFiles }}"
