name: LIQUIBASE-VALIDATOR
on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: checkout
        name: "Check Out del Código"
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Hello world action step
        id: hello
        uses: afajardomorera/liquibase-file-validator@v.1.2
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
