name: SPLIT TEXT TEST

on:
 workflow_dispatch:
   inputs:
     text: 
       type: string

jobs:
  split-text:
    name: Split Text Test
    runs-on: ubuntu-latest
    steps:
      - id: split_text
        name: Split Text
        uses: afajardomorera/split-text@develop
        with:
          text: ${{ inputs.text }}

      - id: result
        name: Test Result
        run: |
          #!/usr/bin/bash 
          echo "Number of items: " ${{ steps.split_text.outputs.number_of_items }}
          echo "item_0: " ${{ steps.split_text.outputs.item_0 }}
          echo "item_1: " ${{ steps.split_text.outputs.item_1 }}
          echo "item_2: " ${{ steps.split_text.outputs.item_2 }}
          counter=0
          while [ $counter -lt ${{ steps.split_text.outputs.number_of_items }} ];
          do
            key = "steps.split_text.outputs.item_"$counter
            echo "Item_"$counter": " $key
          done
