on:
  workflow_call:
    inputs:
      parametro1:
        type: string
        description: "Descripción del parámetro 1"
        default: "Valor Parámetro 1"
jobs:
  test-inputs:
    env: 
      MI_VAR: ${{ inputs.parametro1 }}
    runs-on: ubuntu-20.04
    steps:
      - id: step1
        name: print-input-from-env-var
        run: echo $MI_VAR
